version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  run_model:
    run: stata-mp:latest analysis/00a_cr_create_analysis_dataset.do
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: logs/00a_cr_create_analysis_dataset.txt
